import type { Organ } from "./anatomy-data";
import { spots, withThreeModel, type SpecimenContent } from "./three-models";

/** Teaching specimens built in Three.js (scripts/three-anatomy): focused
 *  organ studies, joints, and regional anatomy. Each `modelNote` says what
 *  is exaggerated or simplified. */
const content: SpecimenContent[] = [
  {
    id: "spleen", name: "Spleen", scientificName: "Splen", system: "Lymphatic System",
    icon: "◒", accent: "#a45d73", illustrated: true, specimenOnly: true,
    description: "A blood-filtering lymphatic organ that removes worn red blood cells and supports immune responses.",
    poetic: "The blood’s quiet guardian", size: "Approximately fist-sized", weight: "Varies with age and body size",
    location: "Upper left abdomen, beside the stomach and beneath the diaphragm",
    function: "Filters blood and supports immune surveillance", dailyFact: "Continuously screens circulating blood",
    medical: "Red pulp filters blood and recycles worn red cells; white pulp gathers lymphocytes around central arteries.",
    bloodSupply: "Splenic artery; venous drainage through the splenic vein",
    funFact: "Unlike lymph nodes, the spleen monitors blood rather than lymph.",
    tissue: "Red pulp and white pulp", comparison: "Spleen vs. lymphatic system",
    conditions: ["Splenomegaly", "Splenic injury", "Splenic infarction", "Hypersplenism"],
    modelNote: "Authored in Three.js: the visceral surface with its notched border and hilum, an oblique section through the lower pole showing red pulp, trabeculae and enlarged white-pulp follicles, the tortuous splenic artery, the splenic vein and the tail of the pancreas. Follicles are not to scale.",
    hotspots: spots(
      ["capsule", "Capsule", "Connective tissue covering of the spleen"],
      ["hilum", "Hilum", "Where vessels enter and leave"],
      ["notches", "Superior Border Notches", "Notches that help identify the spleen"],
      ["red-pulp", "Red Pulp", "Sinusoids that filter blood"],
      ["white-pulp", "White Pulp", "Lymphoid follicles (enlarged)"],
      ["splenic-artery", "Splenic Artery", "Characteristically tortuous branch of the celiac trunk"],
      ["splenic-vein", "Splenic Vein", "Drains toward the hepatic portal vein"],
      ["pancreas-tail", "Tail of Pancreas", "Reaches the splenic hilum"],
    ),
  },
  {
    id: "esophagus", name: "Esophagus", scientificName: "Oesophagus", system: "Digestive System",
    icon: "∿", accent: "#c78176", illustrated: true, specimenOnly: true,
    description: "A muscular passage that moves swallowed food from the pharynx to the stomach through the chest and diaphragm.",
    poetic: "The passage to digestion", size: "About 25 cm long in an adult", weight: "Depends on body size",
    location: "Behind the trachea, through the chest and diaphragm to the stomach", function: "Propels swallowed food by peristalsis",
    dailyFact: "Coordinates muscular waves with each swallow", medical: "The lining protects against abrasion. Muscle transitions from skeletal above to smooth below, with sphincters at each end.",
    bloodSupply: "Regional branches of the inferior thyroid artery, thoracic aorta, and left gastric artery",
    funFact: "Peristaltic waves can move food even when gravity does not assist.", tissue: "Stratified squamous epithelium and muscular wall", comparison: "Esophagus vs. stomach",
    conditions: ["Reflux esophagitis", "Achalasia", "Esophageal stricture", "Barrett esophagus"],
    modelNote: "Authored in Three.js: the full course from the upper sphincter to the cardia, with a stepped window peeling back the longitudinal and circular muscle, submucosa and folded mucosa. The aortic arch, carina, diaphragm and vagal plexus give context; wall layers are exaggerated in thickness.",
    hotspots: spots(
      ["longitudinal-muscle", "Longitudinal Muscle", "Outer layer that shortens the passage"],
      ["circular-muscle", "Circular Muscle", "Inner layer that squeezes food along"],
      ["submucosa", "Submucosa", "Connective tissue with glands and vessels"],
      ["mucosa", "Mucosa", "Folded lining of stratified squamous epithelium"],
      ["upper-sphincter", "Upper Esophageal Sphincter", "Cricopharyngeus closes the top between swallows"],
      ["lower-sphincter", "Lower Esophageal Sphincter", "Limits reflux from the stomach"],
      ["hiatus", "Esophageal Hiatus", "Opening in the diaphragm"],
      ["aortic-arch", "Aortic Arch", "Crosses at the middle narrowing"],
      ["vagal-plexus", "Esophageal Plexus", "Vagal nerve network on the lower esophagus"],
    ),
  },
  {
    id: "knee", name: "Knee", scientificName: "Articulatio genus", system: "Skeletal System",
    icon: "⌘", accent: "#c7ad86", illustrated: true, specimenOnly: true,
    description: "The right knee: registered femur, tibia, fibula, and patella with articular cartilage, menisci, cruciate and collateral ligaments, and the extensor mechanism.",
    poetic: "The hinge of each stride", size: "Connects the thigh to the lower leg", weight: "Varies with body size", location: "Between the thigh and lower leg",
    function: "Enables flexion and extension while transferring body weight", dailyFact: "Alternates support and motion during walking",
    medical: "Cartilage and menisci cushion the joint while the cruciate and collateral ligaments guide and stabilize it.",
    bloodSupply: "Genicular branches around the knee", funFact: "The patella is a sesamoid bone embedded in the quadriceps tendon.",
    tissue: "Bone, articular cartilage, and fibrocartilage", comparison: "Knee vs. skeleton", conditions: ["Osteoarthritis", "Patellar dislocation", "Meniscal injury", "Ligament injury"],
    modelNote: "Registered BodyParts3D bones refined in Three.js, with sectioned shafts showing cortical bone and marrow. Cartilage, menisci, ligaments and tendons are authored from atlas references; the joint capsule and bursae are omitted.",
    hotspots: spots(
      ["femur", "Distal Femur", "Thigh bone ending in the femoral condyles"],
      ["cartilage", "Articular Cartilage", "Smooth covering on the condyles"],
      ["tibia", "Proximal Tibia", "Main weight-bearing bone of the lower leg"],
      ["fibula", "Fibular Head", "Lateral attachment for the collateral ligament"],
      ["patella", "Patella", "Kneecap in front of the femur"],
      ["patellar-ligament", "Patellar Ligament", "Links the patella to the tibial tuberosity"],
      ["menisci", "Menisci", "C-shaped fibrocartilage cushions"],
      ["acl", "Anterior Cruciate Ligament", "Stops the tibia sliding forward"],
      ["pcl", "Posterior Cruciate Ligament", "Stops the tibia sliding backward"],
      ["mcl", "Medial Collateral Ligament", "Resists inward bending of the knee"],
      ["lcl", "Lateral Collateral Ligament", "Resists outward bending of the knee"],
    ),
  },
  {
    id: "tooth", name: "Tooth", scientificName: "Dens molaris", system: "Digestive System",
    icon: "◇", accent: "#d9c69e", illustrated: true, specimenOnly: true,
    description: "A mandibular molar in its socket, sectioned to show the hard tissues of the tooth and the living tissues that anchor and nourish it.",
    poetic: "The quiet grinder", size: "About 20–22 mm from cusp tip to root apex", weight: "Around 2 g",
    location: "At the back of the lower dental arch, set in the alveolar bone of the mandible",
    function: "Grinds food during chewing", dailyFact: "Withstands repeated chewing forces",
    medical: "Enamel is the hardest substance in the body; beneath it, dentin and the living pulp respond to temperature, decay, and wear.",
    bloodSupply: "Inferior alveolar artery, a branch of the maxillary artery",
    funFact: "Enamel cannot regrow: the cells that make it are lost once the tooth erupts.",
    tissue: "Enamel, dentin, pulp, and periodontal ligament", comparison: "Tooth vs. skeleton",
    conditions: ["Dental caries", "Pulpitis", "Periodontitis", "Gingivitis", "Dental abscess", "Enamel erosion", "Impacted tooth", "Dentin hypersensitivity"],
    modelNote: "Authored in Three.js from atlas references: a two-rooted lower molar sectioned through its long axis with enamel, dentin, pulp, cementum, periodontal ligament, alveolar bone, gingiva and the inferior alveolar bundle. Layer thicknesses and the neurovascular branches are simplified.",
    hotspots: spots(
      ["crown", "Crown", "Cusps that meet the opposing teeth"],
      ["enamel", "Enamel", "Hardest tissue in the body, about 96% mineral"],
      ["dentin", "Dentin", "Living, tubular bulk of the tooth"],
      ["pulp", "Pulp Chamber", "Nerves and vessels inside the crown"],
      ["root-canal", "Root Canal", "Carries pulp tissue to the apex"],
      ["cementum", "Cementum", "Thin layer covering the root"],
      ["periodontal-ligament", "Periodontal Ligament", "Suspends the tooth in its socket"],
      ["alveolar-bone", "Alveolar Bone", "Socket of the jaw that holds the roots"],
      ["gingiva", "Gingiva", "Gum tissue sealing around the neck"],
      ["nerve", "Inferior Alveolar Nerve", "Supplies sensation to the lower teeth"],
    ),
  },
  {
    id: "tongue", name: "Tongue", scientificName: "Lingua", system: "Digestive System",
    icon: "◖", accent: "#d98a8c", illustrated: true, specimenOnly: true,
    description: "A muscular organ that shapes and moves food, carries most taste buds, and makes the fine movements of speech.",
    poetic: "The shaper of taste and speech", size: "About 10 cm long in adults", weight: "Roughly 60–70 g",
    location: "Floor of the mouth, extending back to the oropharynx",
    function: "Taste, chewing, swallowing, and speech", dailyFact: "Repositions food hundreds of times during a meal",
    medical: "Four intrinsic muscles change its shape while four extrinsic muscles move it; all but one are supplied by the hypoglossal nerve.",
    bloodSupply: "Lingual artery, a branch of the external carotid",
    funFact: "Taste buds are not limited to the tongue: some sit on the soft palate, pharynx, and epiglottis.",
    tissue: "Papillae, taste buds, and interlacing skeletal muscle", comparison: "Tongue vs. esophagus",
    conditions: ["Glossitis", "Oral thrush", "Tongue-tie", "Geographic tongue", "Oral cancer", "Macroglossia", "Burning mouth syndrome", "Taste disorders"],
    modelNote: "Authored in Three.js from atlas references: the dorsum with median and terminal sulci, circumvallate, fungiform, foliate and filiform papillae and the lingual tonsil, plus the epiglottis, palatine tonsils, hyoid and the extrinsic muscles, nerves and vessels beneath. Papillae are slightly enlarged; their count is representative.",
    hotspots: spots(
      ["apex", "Apex", "Mobile tip of the tongue"],
      ["median-sulcus", "Median Sulcus", "Midline groove of the oral part"],
      ["fungiform", "Fungiform Papillae", "Red, mushroom-shaped papillae with taste buds"],
      ["filiform", "Filiform Papillae", "Fine papillae that give a velvety grip"],
      ["circumvallate", "Circumvallate Papillae", "Large papillae in a V, ringed by moats of taste buds"],
      ["terminal-sulcus", "Terminal Sulcus", "V-shaped boundary of the oral part"],
      ["foliate", "Foliate Papillae", "Folds on the sides near the back"],
      ["lingual-tonsil", "Lingual Tonsil", "Lymphoid nodules on the pharyngeal part"],
      ["epiglottis", "Epiglottis", "Leaf of cartilage that guards the airway"],
      ["genioglossus", "Genioglossus", "Extrinsic muscle that protrudes the tongue"],
    ),
  },
  {
    id: "larynx", name: "Larynx", scientificName: "Larynx", system: "Respiratory System",
    icon: "⌸", accent: "#cba58a", illustrated: true, specimenOnly: true,
    description: "The voice box: a framework of cartilages, ligaments, and muscles that protects the airway and sets the vocal folds vibrating to make sound.",
    poetic: "The voice in the airway", size: "About 4–5 cm tall in adults", weight: "A few tens of grams",
    location: "Front of the neck, from the hyoid bone to the trachea (about C3–C6)",
    function: "Protects the airway and produces voice", dailyFact: "Closes briefly with every swallow",
    medical: "The vocal folds open for breathing and come together to vibrate for voice; the recurrent laryngeal nerves control almost all of its muscles.",
    bloodSupply: "Superior and inferior laryngeal arteries",
    funFact: "During speech the vocal folds typically vibrate between about 100 and 250 times per second.",
    tissue: "Hyaline and elastic cartilage, vocal fold mucosa", comparison: "Larynx vs. airway and diaphragm",
    conditions: ["Laryngitis", "Vocal fold nodules", "Vocal fold paralysis", "Laryngeal cancer", "Croup", "Epiglottitis", "Laryngopharyngeal reflux", "Laryngomalacia"],
    modelNote: "Authored in Three.js: hyoid, thyroid and cricoid cartilages, arytenoids, epiglottis and trachea, with a window through the left thyroid lamina that sections the vocal and vestibular folds in the coronal plane. Membranes, cricothyroid muscles, nerves and arteries are simplified.",
    hotspots: spots(
      ["thyroid-cartilage", "Thyroid Cartilage", "Shield whose prominence forms the Adam’s apple"],
      ["cricoid", "Cricoid Cartilage", "The only complete cartilage ring of the airway"],
      ["hyoid", "Hyoid Bone", "Suspends the larynx from above"],
      ["epiglottis", "Epiglottis", "Folds back to guard the airway during swallowing"],
      ["vocal-folds", "Vocal Folds", "Vibrate to make voice"],
      ["vestibular-folds", "Vestibular Folds", "The protective false cords above"],
      ["ventricle", "Laryngeal Ventricle", "Recess between the two pairs of folds"],
      ["arytenoid", "Arytenoid Cartilage", "Pivots to open and close the vocal folds"],
      ["thyrohyoid-membrane", "Thyrohyoid Membrane", "Joins the larynx to the hyoid"],
      ["cricothyroid", "Cricothyroid Muscle", "Tilts the thyroid cartilage to raise pitch"],
      ["trachea", "Trachea", "Airway continuing below the cricoid"],
    ),
  },
  {
    id: "adrenal-glands", name: "Adrenal Glands", scientificName: "Glandulae suprarenales", system: "Endocrine System",
    icon: "◬", accent: "#d6a24a", illustrated: true, specimenOnly: true,
    description: "Paired endocrine glands on the kidneys whose cortex makes steroid hormones and whose medulla releases adrenaline.",
    poetic: "The glands of readiness", size: "Each about 5 cm long and 1 cm thick", weight: "About 4–5 g each",
    location: "On the upper pole of each kidney, behind the peritoneum",
    function: "Produces cortisol, aldosterone, adrenal androgens, and adrenaline", dailyFact: "Follows a daily cortisol rhythm that peaks in the morning",
    medical: "The cortex has three zones — glomerulosa, fasciculata, and reticularis — around a medulla of chromaffin cells.",
    bloodSupply: "Superior, middle, and inferior suprarenal arteries",
    funFact: "The right gland is pyramidal and drains straight into the vena cava; the left is crescentic and drains into the left renal vein.",
    tissue: "Adrenal cortex zones and chromaffin cells", comparison: "Adrenal glands vs. thyroid",
    conditions: ["Addison disease", "Cushing syndrome", "Primary aldosteronism", "Pheochromocytoma", "Congenital adrenal hyperplasia", "Adrenal insufficiency", "Adrenal incidentaloma", "Adrenocortical carcinoma"],
    modelNote: "Authored in Three.js: both glands on the upper poles of the kidneys, the left sectioned to show its cortical zones and medulla, with the aorta, inferior vena cava and suprarenal vessels. Zone thicknesses and vessel calibre are exaggerated; the kidneys are cut below their hila.",
    hotspots: spots(
      ["right-adrenal", "Right Adrenal Gland", "Pyramidal gland on the right kidney"],
      ["left-adrenal", "Left Adrenal Gland", "Crescent along the left kidney"],
      ["cortex", "Adrenal Cortex", "Zones that make aldosterone, cortisol, and androgens"],
      ["medulla", "Adrenal Medulla", "Releases adrenaline and noradrenaline"],
      ["suprarenal-arteries", "Suprarenal Arteries", "Three sources feed each gland"],
      ["right-suprarenal-vein", "Right Suprarenal Vein", "Short vein straight into the vena cava"],
      ["left-suprarenal-vein", "Left Suprarenal Vein", "Drains into the left renal vein"],
      ["kidney", "Kidney", "Upper pole beneath the gland"],
      ["aorta", "Abdominal Aorta", "Gives the middle suprarenal arteries"],
    ),
  },
  {
    id: "lumbar-spine", name: "Lumbar Spine", scientificName: "Vertebrae lumbales", system: "Skeletal System",
    icon: "≣", accent: "#c9b08c", illustrated: true, specimenOnly: true,
    description: "The lower back’s stack of large vertebrae and discs, sectioned down the midline to show the bone, discs, ligaments, and nerve roots inside.",
    poetic: "The column that carries us", size: "Five vertebrae, each body about 4–5 cm wide", weight: "Varies with body size",
    location: "Lower back, between the rib cage and the sacrum",
    function: "Bears body weight, allows bending, and protects the cauda equina", dailyFact: "Discs lose and regain fluid each day",
    medical: "Each disc pairs a tough ring of fibrocartilage lamellae with a gel-like nucleus that spreads load between vertebral bodies.",
    bloodSupply: "Lumbar arteries arising from the abdominal aorta",
    funFact: "Most people are about a centimetre taller in the morning, because discs rehydrate overnight.",
    tissue: "Cancellous bone, annulus fibrosus, and nucleus pulposus", comparison: "Lumbar spine vs. spinal cord",
    conditions: ["Herniated disc", "Degenerative disc disease", "Spinal stenosis", "Spondylolisthesis", "Vertebral compression fracture", "Sciatica", "Ankylosing spondylitis", "Scoliosis"],
    modelNote: "Registered BodyParts3D vertebrae (L2 to the sacrum) and discs halved at the midline in Three.js, with painted cancellous bone and disc lamellae. The dural sac, cauda equina, exiting roots and spinal ligaments are authored from atlas references; root counts are representative. Turn the model to see the intact right side.",
    hotspots: spots(
      ["vertebral-body", "Vertebral Body", "Weight-bearing block of cancellous bone"],
      ["annulus", "Annulus Fibrosus", "Lamellae of the disc’s outer ring"],
      ["nucleus", "Nucleus Pulposus", "Gel-like core of the disc"],
      ["spinous-process", "Spinous Process", "Lever for back muscles and ligaments"],
      ["cauda-equina", "Cauda Equina", "Nerve roots descending in the dural sac"],
      ["nerve-root", "Spinal Nerve Root", "Leaves through the intervertebral foramen"],
      ["anterior-ligament", "Anterior Longitudinal Ligament", "Runs down the front of the bodies"],
      ["ligamentum-flavum", "Ligamentum Flavum", "Elastic yellow ligament between laminae"],
      ["sacrum", "Sacrum", "Fused vertebrae joining the pelvis"],
    ),
  },
  {
    id: "hand", name: "Hand", scientificName: "Manus", system: "Skeletal System",
    icon: "✋", accent: "#d2b98f", illustrated: true, specimenOnly: true,
    description: "The bones of the right hand and wrist seen from the palm, with the carpal tunnel and the median nerve that passes through it.",
    poetic: "The instrument of touch", size: "About 18–20 cm from wrist to fingertip", weight: "Varies with body size",
    location: "Beyond the forearm, joined at the wrist",
    function: "Grasps, manipulates, and explores by touch", dailyFact: "Makes thousands of precise movements",
    medical: "Eight carpals, five metacarpals, and fourteen phalanges form each hand; the thumb’s saddle joint lets it oppose the fingers.",
    bloodSupply: "Superficial and deep palmar arches from the radial and ulnar arteries",
    funFact: "With 27 bones each, the two hands hold more than a quarter of the body’s bones.",
    tissue: "Compact bone and articular cartilage", comparison: "Hand vs. skeleton",
    conditions: ["Carpal tunnel syndrome", "Scaphoid fracture", "Osteoarthritis", "Rheumatoid arthritis", "Boxer’s fracture", "Trigger finger", "Dupuytren contracture", "De Quervain tenosynovitis"],
    modelNote: "Registered BodyParts3D bones of the right hand, refined in Three.js, with the distal radius and ulna sectioned. The flexor retinaculum and median nerve are authored from atlas references; tendons, muscles and skin are omitted.",
    hotspots: spots(
      ["scaphoid", "Scaphoid", "Most commonly fractured carpal bone"],
      ["carpals", "Carpal Bones", "Eight small bones of the wrist"],
      ["metacarpals", "Metacarpals", "Five bones of the palm"],
      ["phalanges", "Phalanges", "Fourteen finger bones"],
      ["thumb", "First Metacarpal", "Saddle joint lets the thumb oppose"],
      ["radius", "Radius", "Forearm bone on the thumb side"],
      ["ulna", "Ulna", "Forearm bone on the little-finger side"],
      ["flexor-retinaculum", "Flexor Retinaculum", "Roof of the carpal tunnel"],
      ["median-nerve", "Median Nerve", "Passes through the carpal tunnel"],
    ),
  },
];

export const additionalOrgans: Organ[] = content.map(withThreeModel);
