import type { Organ } from "./anatomy-data";
import { spots, withThreeModel, type SpecimenContent } from "./three-models";

/**
 * The second collection expands the atlas from isolated organs into the body
 * systems learners most often meet next. Each entry deliberately uses the
 * same data contract as the original specimens, so notes, comparisons,
 * lessons, quizzes, progress, deep links, and analytics work without a second
 * class of content. Models and hotspot anchors come from scripts/three-anatomy.
 */
const content: SpecimenContent[] = [
  {
    id: "stomach",
    name: "Stomach",
    scientificName: "Gaster",
    system: "Digestive System",
    icon: "◒",
    accent: "#d47d70",
    description: "A muscular chamber that stores a meal, mixes it with acid and enzymes, and meters partially digested food into the small intestine.",
    poetic: "The patient mixer",
    size: "Roughly 25–30 cm along its longest curve",
    weight: "About 150 g when empty",
    location: "Upper left abdomen beneath the diaphragm",
    function: "Stores, churns, and begins digesting food",
    dailyFact: "Produces roughly 2–3 L of gastric fluid",
    medical: "Rugae let the stomach expand while coordinated muscle layers turn a meal into chyme.",
    bloodSupply: "Branches of the celiac trunk",
    funFact: "Its lining replaces surface cells rapidly to withstand an environment acidic enough to unfold many proteins.",
    tissue: "Gastric mucosa and glands",
    comparison: "Stomach vs. intestine",
    conditions: ["Gastritis", "Peptic ulcer disease", "Gastroesophageal reflux", "Gastroparesis", "Gastric polyps", "Hiatal hernia", "Gastric cancer", "Pyloric stenosis"],
    illustrated: true,
    modelNote: "Authored in Three.js from atlas references: a J-shaped stomach with an anterior window onto the rugae and the cut wall layers, the gastric and gastroepiploic arcades, and cut edges of the omentum. Wall thickness, fold height and vessel calibre are exaggerated for study.",
    hotspots: spots(
      ["cardia", "Cardia", "Receives food from the esophagus"],
      ["fundus", "Fundus", "Rounded upper reservoir above the cardia"],
      ["body", "Body", "Main mixing chamber"],
      ["rugae", "Rugae", "Mucosal folds that flatten as the stomach fills"],
      ["antrum", "Pyloric Antrum", "Grinds food before it leaves the stomach"],
      ["pylorus", "Pylorus", "Sphincter that meters chyme into the duodenum"],
      ["gastroepiploic", "Gastric Arteries", "Arcades along the curvatures from the celiac trunk"],
    ),
  },
  {
    id: "skeleton",
    name: "Skeleton",
    scientificName: "Systema skeletale",
    system: "Skeletal System",
    icon: "⌘",
    accent: "#c7ad86",
    description: "The body’s framework of bones, cartilage, and ligaments, built to support movement, protect organs, store minerals, and house blood-forming marrow.",
    poetic: "The living scaffold",
    size: "206 bones in the typical adult skeleton",
    weight: "Roughly 12–15% of body mass",
    location: "From the skull to the bones of the feet",
    function: "Supports, protects, stores minerals, and enables movement",
    dailyFact: "Constantly remodels old and new bone",
    medical: "Axial bones form the central support while appendicular bones create the levers of the limbs.",
    bloodSupply: "Nutrient, periosteal, metaphyseal, and epiphyseal vessels",
    funFact: "Bone is living tissue: cells continually remove tiny regions and rebuild them in response to load and mineral needs.",
    tissue: "Compact bone, spongy bone, and marrow",
    comparison: "Skeleton vs. muscles",
    conditions: ["Osteoporosis", "Fracture", "Osteoarthritis", "Scoliosis", "Osteomyelitis", "Rickets", "Paget disease of bone", "Osteosarcoma"],
    illustrated: true,
    modelNote: "Registered BodyParts3D scans of 265 bones, cartilages, discs and teeth, including the hands, feet, sternum and costal cartilages, smoothed and painted in Three.js. Articular cartilage is suggested by colour rather than modelled as a separate layer.",
    hotspots: spots(
      ["skull", "Skull", "Protects the brain and shapes the face"],
      ["spine", "Vertebral Column", "Supports the trunk and encloses the spinal cord"],
      ["ribcage", "Thoracic Cage", "Ribs guard the heart and lungs"],
      ["sternum", "Sternum", "Breastbone joined to the ribs by costal cartilage"],
      ["clavicle", "Clavicle", "Strut linking the arm to the trunk"],
      ["humerus", "Humerus", "Bone of the upper arm"],
      ["pelvis", "Pelvis", "Transfers trunk weight to the legs"],
      ["hand", "Bones of the Hand", "27 bones: carpals, metacarpals, and phalanges"],
      ["femur", "Femur", "The body’s longest bone"],
      ["patella", "Patella", "Sesamoid bone in the quadriceps tendon"],
      ["foot", "Bones of the Foot", "Tarsals, metatarsals, and phalanges form the arches"],
    ),
  },
  {
    id: "muscles",
    name: "Muscles",
    scientificName: "Musculi skeletales",
    system: "Muscular System",
    icon: "∿",
    accent: "#b95f56",
    description: "Hundreds of skeletal muscles pull on tendons and bones to create movement, stabilize joints, maintain posture, and generate heat.",
    poetic: "The body in motion",
    size: "More than 600 named skeletal muscles",
    weight: "About 30–40% of body mass in many adults",
    location: "Layered throughout the face, trunk, and limbs",
    function: "Creates movement, posture, stability, and heat",
    dailyFact: "Makes countless coordinated contractions",
    medical: "Motor units let the nervous system grade force from delicate control to powerful whole-limb movement.",
    bloodSupply: "Regional muscular branches of nearby arteries",
    funFact: "Muscles can pull but cannot push, so many movements depend on opposing muscle groups taking turns.",
    tissue: "Skeletal muscle fibers and fascicles",
    comparison: "Muscles vs. skeleton",
    conditions: ["Muscle strain", "Tendinopathy", "Muscular dystrophy", "Myositis", "Rhabdomyolysis", "Myasthenia gravis", "Fibromyalgia", "Sarcopenia"],
    illustrated: true,
    modelNote: "About 140 registered BodyParts3D muscle surfaces over the skeleton, with fascicles painted along each muscle’s long axis and pale tendon toward its ends. Deep muscles hidden beneath the superficial layer are left out.",
    hotspots: spots(
      ["deltoid", "Deltoid", "Raises and stabilizes the arm"],
      ["pectoralis", "Pectoralis Major", "Moves the arm across the chest"],
      ["biceps", "Biceps Brachii", "Flexes the elbow and turns the palm up"],
      ["rectus", "Rectus Abdominis", "Flexes and braces the trunk"],
      ["sternocleidomastoid", "Sternocleidomastoid", "Turns and flexes the head"],
      ["quadriceps", "Quadriceps", "Extends the knee"],
      ["sartorius", "Sartorius", "The body’s longest muscle, crossing hip and knee"],
      ["tibialis", "Tibialis Anterior", "Lifts the foot at the ankle"],
      ["gastrocnemius", "Gastrocnemius", "Powers plantar flexion at the ankle"],
      ["gluteus", "Gluteus Maximus", "Extends the hip when climbing and rising"],
      ["trapezius", "Trapezius", "Moves and steadies the shoulder blade"],
    ),
  },
  {
    id: "ear",
    name: "Ear",
    scientificName: "Auris",
    system: "Sensory System",
    icon: "◔",
    accent: "#c98673",
    description: "A layered sensory system that gathers sound, converts vibration into nerve signals, and measures head movement for balance.",
    poetic: "The keeper of sound",
    size: "Inner structures fit within the temporal bone",
    weight: "Only a few grams of sensory structures",
    location: "At each side of the head and within the temporal bone",
    function: "Supports hearing and equilibrium",
    dailyFact: "Tracks sound and head motion continuously",
    medical: "The cochlea handles hearing while the vestibular apparatus detects rotation and linear acceleration.",
    bloodSupply: "Posterior auricular, superficial temporal, and labyrinthine arteries",
    funFact: "The three semicircular canals sit in different planes, allowing the brain to detect rotation in three dimensions.",
    tissue: "Cochlear hair cells and vestibular epithelium",
    comparison: "Ear vs. eye",
    conditions: ["Otitis media", "Hearing loss", "Tinnitus", "Vertigo", "Ménière disease", "Otosclerosis", "Perforated eardrum", "Labyrinthitis"],
    illustrated: true,
    specimenOnly: true,
    modelNote: "A coronal section through the temporal bone authored in Three.js: auricle, external canal, tympanic membrane, the three ossicles, cochlea, vestibule and semicircular canals, auditory tube, and cranial nerves VII and VIII. Middle and inner ear structures are enlarged relative to the auricle so they can be read.",
    hotspots: spots(
      ["auricle", "Auricle", "Cartilage-supported outer ear that funnels sound"],
      ["ear-canal", "External Auditory Canal", "Carries sound to the eardrum"],
      ["tympanic-membrane", "Tympanic Membrane", "Vibrates with incoming sound"],
      ["malleus", "Malleus", "First ossicle, fixed to the eardrum"],
      ["incus", "Incus", "Middle ossicle linking malleus and stapes"],
      ["stapes", "Stapes", "Smallest bone; rocks in the oval window"],
      ["vestibule", "Vestibule", "Senses head tilt and linear acceleration"],
      ["semicircular-canals", "Semicircular Canals", "Three loops that sense rotation"],
      ["cochlea", "Cochlea", "Turns vibration into neural signals"],
      ["auditory-tube", "Auditory Tube", "Equalizes middle-ear pressure with the throat"],
      ["vestibulocochlear-nerve", "Vestibulocochlear Nerve", "Carries hearing and balance signals to the brainstem"],
    ),
  },
  {
    id: "spinal-cord",
    name: "Spinal Cord",
    scientificName: "Medulla spinalis",
    system: "Nervous System",
    icon: "⋮",
    accent: "#d4a16f",
    description: "A long column of nervous tissue that relays information between brain and body and organizes rapid reflexes close to their source.",
    poetic: "The signal highway",
    size: "About 42–45 cm long in adults",
    weight: "Approximately 30–35 g",
    location: "Within the vertebral canal, ending near L1–L2",
    function: "Carries sensory, motor, and reflex signals",
    dailyFact: "Coordinates signals for every region below the head",
    medical: "Thirty-one pairs of spinal nerves connect cord segments with predictable regions of skin and muscle.",
    bloodSupply: "Anterior and paired posterior spinal arteries",
    funFact: "Some protective reflexes are organized in the spinal cord before the brain has consciously registered what happened.",
    tissue: "Central gray matter and surrounding white matter",
    comparison: "Spinal cord vs. brain",
    conditions: ["Spinal cord injury", "Transverse myelitis", "Spinal stenosis", "Syringomyelia", "Multiple sclerosis", "Spina bifida", "Cord compression", "Amyotrophic lateral sclerosis"],
    illustrated: true,
    specimenOnly: true,
    modelNote: "Authored in Three.js: the whole cord at true proportions with all 31 nerve pairs and the cauda equina, beside one segment enlarged and opened to show gray and white matter, rootlets, dorsal root ganglia, dura mater and spinal arteries.",
    hotspots: spots(
      ["cervical", "Cervical Enlargement", "Supplies the upper limbs"],
      ["thoracic", "Thoracic Cord", "Connects with the trunk"],
      ["lumbar", "Lumbar Enlargement", "Supplies the lower limbs"],
      ["cauda", "Cauda Equina", "Bundle of lower nerve roots below the cord"],
      ["grey-matter", "Gray Matter", "Butterfly of neuron cell bodies and synapses"],
      ["white-matter", "White Matter", "Columns of ascending and descending tracts"],
      ["dorsal-root", "Dorsal Root", "Carries sensory fibers into the cord"],
      ["ventral-root", "Ventral Root", "Carries motor fibers out of the cord"],
      ["ganglion", "Dorsal Root Ganglion", "Holds the cell bodies of sensory neurons"],
      ["dura", "Dura Mater", "Tough outer membrane, opened here"],
      ["spinal-artery", "Anterior Spinal Artery", "Runs in the anterior median fissure"],
    ),
  },
  {
    id: "bladder",
    name: "Bladder",
    scientificName: "Vesica urinaria",
    system: "Urinary System",
    icon: "◡",
    accent: "#d49a68",
    description: "A stretchable muscular reservoir that receives urine from the ureters and stores it until coordinated emptying through the urethra.",
    poetic: "The quiet reservoir",
    size: "Comfortably holds about 400–600 mL in many adults",
    weight: "Varies with filling",
    location: "Behind the pubic bones in the pelvis",
    function: "Stores and releases urine",
    dailyFact: "Fills and empties several times each day",
    medical: "The detrusor muscle and urinary sphincters coordinate storage with voluntary and reflex control.",
    bloodSupply: "Superior and inferior vesical arteries",
    funFact: "As it fills, folds in the inner lining flatten so volume can rise without a matching jump in pressure.",
    tissue: "Transitional epithelium and detrusor muscle",
    comparison: "Bladder vs. kidneys",
    conditions: ["Urinary tract infection", "Overactive bladder", "Urinary retention", "Interstitial cystitis", "Bladder stones", "Urinary incontinence", "Neurogenic bladder", "Bladder cancer"],
    illustrated: true,
    specimenOnly: true,
    modelNote: "Authored in Three.js: an anterior window shows the rugae, the smooth trigone with its ureteric orifices, and the detrusor in section. Wall thickness, fold height and the interlacing muscle bundles are exaggerated for study.",
    hotspots: spots(
      ["detrusor", "Detrusor Muscle", "Contracts to empty the bladder"],
      ["urothelium", "Urothelium", "Stretchy lining folded into rugae"],
      ["trigone", "Trigone", "Smooth triangle between the three openings"],
      ["ureteric-orifice", "Ureteric Orifice", "Slit where a ureter enters"],
      ["ureters", "Ureters", "Deliver urine from the kidneys"],
      ["urethra", "Urethra", "Carries urine out of the body"],
      ["apex", "Median Umbilical Ligament", "Remnant of the fetal urachus at the apex"],
    ),
  },
  {
    id: "thyroid",
    name: "Thyroid",
    scientificName: "Glandula thyroidea",
    system: "Endocrine System",
    icon: "⋈",
    accent: "#b96d63",
    description: "A butterfly-shaped endocrine gland whose hormones help set the pace of metabolism, growth, temperature regulation, and cardiovascular activity.",
    poetic: "The metabolic metronome",
    size: "About 4–6 cm across",
    weight: "Usually about 20–30 g",
    location: "Front of the neck, wrapped around the upper trachea",
    function: "Produces hormones that regulate metabolic activity",
    dailyFact: "Continuously adjusts hormone output through feedback",
    medical: "Follicles store thyroid hormone precursor outside their cells, an unusual arrangement among endocrine glands.",
    bloodSupply: "Superior and inferior thyroid arteries",
    funFact: "Despite its small size, it receives a rich blood supply so hormone output can respond efficiently to feedback signals.",
    tissue: "Thyroid follicles and parafollicular cells",
    comparison: "Thyroid vs. pancreas",
    conditions: ["Hypothyroidism", "Hyperthyroidism", "Hashimoto thyroiditis", "Graves disease", "Thyroid nodules", "Goiter", "Thyroiditis", "Thyroid cancer"],
    illustrated: true,
    specimenOnly: true,
    modelNote: "Authored in Three.js: the gland with its isthmus and pyramidal lobe on the larynx and trachea, the left lobe sectioned to show follicles, posterior parathyroids, thyroid vessels, carotids and jugulars, and the recurrent laryngeal nerves. Follicles are enlarged far beyond life size.",
    hotspots: spots(
      ["right-lobe", "Right Lobe", "One half of the gland"],
      ["left-lobe", "Left Lobe", "Sectioned to show its interior"],
      ["follicles", "Follicles", "Store colloid, the hormone precursor (enlarged)"],
      ["isthmus", "Isthmus", "Connects the two lobes across the trachea"],
      ["pyramidal-lobe", "Pyramidal Lobe", "Common upward extension of the isthmus"],
      ["parathyroid", "Parathyroid Glands", "Four small glands that control blood calcium"],
      ["superior-thyroid-artery", "Superior Thyroid Artery", "First branch of the external carotid"],
      ["trachea", "Trachea", "The gland hugs the airway"],
      ["thyroid-cartilage", "Thyroid Cartilage", "The laryngeal prominence above the gland"],
    ),
  },
  {
    id: "lymphatic",
    name: "Spleen & Lymph Nodes",
    scientificName: "Systema lymphaticum",
    system: "Lymphatic & Immune System",
    icon: "⁙",
    accent: "#a85e70",
    description: "A distributed defense and fluid-return network in which lymph vessels and nodes survey tissue fluid while the spleen filters blood.",
    poetic: "The watchful network",
    size: "The spleen is roughly 12 cm long; nodes are usually millimetres across",
    weight: "The spleen commonly weighs about 150 g",
    location: "Nodes follow vessels throughout the body; the spleen sits upper left abdomen",
    function: "Returns tissue fluid and supports immune surveillance",
    dailyFact: "Filters lymph and blood around the clock",
    medical: "Lymph nodes expose immune cells to material arriving from defined drainage regions, while the spleen monitors the bloodstream.",
    bloodSupply: "Splenic artery; nodal branches from regional vessels",
    funFact: "Unlike lymph nodes, which filter lymph, the spleen filters blood and can remove aging red blood cells from circulation.",
    tissue: "Lymphoid follicles, red pulp, and white pulp",
    comparison: "Lymphatic network vs. bloodstream",
    conditions: ["Lymphadenopathy", "Lymphedema", "Splenomegaly", "Lymphoma", "Splenic rupture", "Tonsillitis", "Lymphangitis", "Immune deficiency"],
    illustrated: true,
    specimenOnly: true,
    modelNote: "Node groups, beaded collecting vessels, the cisterna chyli, thoracic and right lymphatic ducts, spleen, thymus and tonsils authored in Three.js over a registered BodyParts3D skeletal frame (rib cage omitted for visibility). Nodes and vessels are enlarged and shown in the atlas convention of green; node counts are representative.",
    hotspots: spots(
      ["cervical", "Cervical Nodes", "Drain the head and neck"],
      ["axillary", "Axillary Nodes", "Drain the upper limbs and chest wall"],
      ["mediastinal", "Mediastinal Nodes", "Drain the lungs and heart"],
      ["thoracic-duct", "Thoracic Duct", "Returns most of the body’s lymph to blood"],
      ["cisterna-chyli", "Cisterna Chyli", "Collecting sac where the thoracic duct begins"],
      ["mesenteric", "Mesenteric Nodes", "Filter lymph and absorbed fat from the gut"],
      ["inguinal", "Inguinal Nodes", "Drain the lower limb and lower trunk"],
      ["spleen", "Spleen", "Filters blood and supports immune responses"],
      ["thymus", "Thymus", "Where T cells mature, largest in childhood"],
      ["tonsils", "Palatine Tonsils", "Guard the entrance to the throat"],
      ["venous-angle", "Venous Angle", "Where lymph re-enters the bloodstream"],
    ),
  },
  {
    id: "female-reproductive",
    name: "Uterus & Ovaries",
    scientificName: "Organa genitalia feminina",
    system: "Reproductive System",
    icon: "⌇",
    accent: "#bf718b",
    description: "A coordinated reproductive system in which ovaries release oocytes and hormones while the uterine tube and uterus support transport, implantation, and pregnancy.",
    poetic: "The cycle of possibility",
    size: "A nonpregnant uterus is roughly 7–8 cm long",
    weight: "Often about 50–80 g before pregnancy",
    location: "Within the pelvis between the bladder and rectum",
    function: "Produces oocytes and supports fertilization, implantation, and pregnancy",
    dailyFact: "Changes continuously across the reproductive cycle",
    medical: "The endometrium responds to ovarian hormones while the muscular myometrium provides the force of labor.",
    bloodSupply: "Uterine and ovarian arteries",
    funFact: "During pregnancy the uterus expands dramatically, then gradually returns toward its earlier size after birth.",
    tissue: "Endometrium, myometrium, and ovarian follicles",
    comparison: "Uterus and ovaries vs. testes and prostate",
    conditions: ["Endometriosis", "Uterine fibroids", "Ovarian cysts", "Polycystic ovary syndrome", "Pelvic inflammatory disease", "Endometrial cancer", "Ovarian cancer", "Uterine prolapse"],
    illustrated: true,
    specimenOnly: true,
    modelNote: "Authored in Three.js: the right half of the uterus, cervix and vagina is opened in the coronal plane and the right ovary bisected to show follicles and a corpus luteum. Tubes, fimbriae, supporting ligaments and the tortuous uterine and ovarian vessels are included; the broad ligament sheet is omitted.",
    hotspots: spots(
      ["uterus", "Uterus", "Supports implantation and pregnancy"],
      ["myometrium", "Myometrium", "Thick smooth muscle that powers labor"],
      ["endometrium", "Endometrium", "Lining that changes across the cycle"],
      ["cervix", "Cervix", "Lower uterine passage with its canal"],
      ["vagina", "Vagina", "Muscular canal below the cervix"],
      ["tubes", "Uterine Tubes", "Carry the oocyte toward the uterus"],
      ["fimbriae", "Fimbriae", "Finger-like fringe that sweeps up the oocyte"],
      ["ovaries", "Ovaries", "Release oocytes and hormones"],
      ["follicles", "Ovarian Follicles", "Develop oocytes; one becomes the corpus luteum"],
      ["uterine-artery", "Uterine Artery", "Climbs tortuously along the uterus"],
      ["round-ligament", "Round Ligament", "Runs from the uterus toward the groin"],
    ),
  },
  {
    id: "male-reproductive",
    name: "Testes & Prostate",
    scientificName: "Organa genitalia masculina",
    system: "Reproductive System",
    icon: "⌁",
    accent: "#a97565",
    description: "A reproductive network in which the testes produce sperm and testosterone while ducts and glands prepare and transport seminal fluid.",
    poetic: "The generative pathway",
    size: "Each testis is about 4–5 cm long; the prostate is walnut-sized",
    weight: "Each testis about 15–25 g; prostate about 20–30 g",
    location: "Testes within the scrotum; prostate below the bladder",
    function: "Produces sperm and reproductive hormones, then supports transport",
    dailyFact: "Maintains sperm production after puberty",
    medical: "Sperm mature in the epididymis before traveling through the ductus deferens and joining glandular secretions.",
    bloodSupply: "Testicular, deferential, and prostatic arterial branches",
    funFact: "The pampiniform venous plexus exchanges heat with incoming arterial blood to help keep the testes cooler than core temperature.",
    tissue: "Seminiferous tubules and prostatic glands",
    comparison: "Testes and prostate vs. uterus and ovaries",
    conditions: ["Benign prostatic hyperplasia", "Prostatitis", "Prostate cancer", "Testicular torsion", "Testicular cancer", "Epididymitis", "Varicocele", "Male factor infertility"],
    illustrated: true,
    specimenOnly: true,
    modelNote: "Authored in Three.js: the bladder base, a coronally sectioned prostate with the urethra and ejaculatory ducts, seminal vesicles, deferent ducts, spermatic cords with the pampiniform plexus, bulbourethral glands and both testes, one opened to show lobules and septa. The penis and scrotal wall are omitted; tubule pattern and scale are schematic.",
    hotspots: spots(
      ["prostate", "Prostate", "Surrounds the urethra below the bladder"],
      ["urethra", "Urethra", "Shared passage for urine and semen"],
      ["vesicles", "Seminal Vesicles", "Add nutrient-rich glandular fluid"],
      ["ductus", "Ductus Deferens", "Transports sperm toward the pelvis"],
      ["testes", "Testes", "Produce sperm and testosterone"],
      ["seminiferous-tubules", "Seminiferous Tubules", "Coiled in lobules where sperm form"],
      ["epididymis", "Epididymis", "Supports sperm maturation"],
      ["spermatic-cord", "Pampiniform Plexus", "Venous network that cools arterial blood"],
      ["bulbourethral", "Bulbourethral Glands", "Pea-sized glands beside the urethra"],
    ),
  },
  {
    id: "gallbladder",
    name: "Gallbladder",
    scientificName: "Vesica biliaris",
    system: "Digestive System",
    icon: "◜",
    accent: "#8d9e5d",
    description: "A small pear-shaped sac that stores and concentrates bile, then releases it into the small intestine when dietary fat arrives.",
    poetic: "The keeper of bile",
    size: "Usually about 7–10 cm long",
    weight: "Varies with its bile volume",
    location: "Tucked beneath the right lobe of the liver",
    function: "Stores, concentrates, and releases bile",
    dailyFact: "Concentrates bile between meals",
    medical: "Contraction of the gallbladder and relaxation of the biliary outlet help deliver bile into the duodenum.",
    bloodSupply: "Cystic artery, usually from the right hepatic artery",
    funFact: "People can live without a gallbladder because the liver still makes bile; storage and timing simply change.",
    tissue: "Folded columnar mucosa and smooth muscle",
    comparison: "Gallbladder vs. liver",
    conditions: ["Gallstones", "Cholecystitis", "Biliary colic", "Choledocholithiasis", "Cholangitis", "Gallbladder polyps", "Biliary dyskinesia", "Gallbladder cancer"],
    illustrated: true,
    specimenOnly: true,
    modelNote: "Authored in Three.js: a windowed gallbladder showing its honeycomb mucosa, the biliary tree to the major duodenal papilla in an opened duodenum, a sectioned head of pancreas, the cystic and hepatic arteries and the portal vein. The liver is omitted; wall thickness and fold height are exaggerated.",
    hotspots: spots(
      ["fundus", "Fundus", "Rounded distal end"],
      ["body", "Body", "Main storage chamber"],
      ["mucosa", "Mucosa", "Honeycomb folds that concentrate bile"],
      ["neck", "Neck", "Narrows toward the cystic duct"],
      ["cystic-duct", "Cystic Duct", "Spiral-valved duct to the biliary tree"],
      ["common-hepatic-duct", "Common Hepatic Duct", "Drains bile from the liver"],
      ["common-bile-duct", "Common Bile Duct", "Carries bile to the duodenum"],
      ["papilla", "Major Duodenal Papilla", "Where bile and pancreatic juice enter the gut"],
      ["cystic-artery", "Cystic Artery", "Usually from the right hepatic artery"],
    ),
  },
  {
    id: "airway-diaphragm",
    name: "Airway & Diaphragm",
    scientificName: "Viae respiratoriae",
    system: "Respiratory System",
    icon: "ϟ",
    accent: "#7794ad",
    description: "A coordinated passage and pump in which the trachea conducts air, the esophagus carries food behind it, and the diaphragm changes chest volume for breathing.",
    poetic: "The crossing of breath",
    size: "Trachea about 10–12 cm; diaphragm spans the lower ribcage",
    weight: "A composite of airway and skeletal muscle structures",
    location: "From the lower neck through the chest to its muscular floor",
    function: "Conducts air, protects swallowing, and powers ventilation",
    dailyFact: "The diaphragm drives most quiet breaths",
    medical: "Cartilage keeps the trachea open, peristalsis moves food through the esophagus, and diaphragm contraction enlarges the thorax.",
    bloodSupply: "Inferior thyroid, bronchial, esophageal, and phrenic arteries",
    funFact: "The esophagus passes through its own opening in the diaphragm before joining the stomach below the chest.",
    tissue: "Ciliated airway epithelium, smooth muscle, and skeletal muscle",
    comparison: "Airway and diaphragm vs. lungs",
    conditions: ["Asthma", "Tracheal stenosis", "Gastroesophageal reflux", "Hiatal hernia", "Diaphragmatic paralysis", "Tracheitis", "Esophagitis", "Aspiration"],
    illustrated: true,
    modelNote: "Authored in Three.js: larynx, ringed trachea and a bronchial tree with true lobar branching, pulmonary arteries alongside the bronchi, the esophagus, both diaphragm domes with the trefoil central tendon and crura, aorta, vena cava and phrenic nerves. Lungs are omitted so the tree can be followed; small-airway branching is representative.",
    hotspots: spots(
      ["larynx", "Larynx", "Voice box guarding the airway"],
      ["trachea", "Trachea", "Cartilage-supported airway"],
      ["carina", "Carina", "Point where the trachea divides"],
      ["main-bronchi", "Main Bronchi", "The right is shorter, wider, and more vertical"],
      ["lobar-bronchi", "Lobar Bronchi", "Three on the right, two on the left"],
      ["esophagus", "Esophagus", "Muscular food passage behind the airway"],
      ["diaphragm", "Diaphragm", "Primary muscle of quiet breathing"],
      ["central-tendon", "Central Tendon", "Trefoil aponeurosis at the top of the dome"],
      ["hiatus", "Esophageal Hiatus", "Opening for the esophagus"],
      ["phrenic-nerve", "Phrenic Nerve", "C3–C5 motor supply to the diaphragm"],
      ["pulmonary-artery", "Pulmonary Arteries", "Follow the bronchi into each lobe"],
    ),
  },
];

export const expandedOrgans: Organ[] = content.map(withThreeModel);
