import type { Organ } from "./anatomy-data";

/**
 * The second collection expands the atlas from isolated organs into the body
 * systems learners most often meet next. Each entry deliberately uses the
 * same data contract as the original specimens, so notes, comparisons,
 * lessons, quizzes, progress, deep links, and analytics work without a second
 * class of content.
 */
export const expandedOrgans: Organ[] = [
  {
    id: "stomach",
    name: "Stomach",
    scientificName: "Gaster",
    system: "Digestive System",
    model: "procedural:stomach",
    icon: "◒",
    accent: "#d47d70",
    description: "A muscular chamber that stores a meal, mixes it with acid and enzymes, and meters partially digested food into the small intestine.",
    poetic: "The patient mixer",
    size: "Roughly 25–30 cm along its longest curve",
    weight: "About 150 g when empty",
    location: "Upper left abdomen beneath the diaphragm",
    function: "Stores, churns, and begins digesting food",
    dailyFact: "Produces roughly 2–3 L of gastric fluid",
    medical: "Rugae let the stomach expand while coordinated muscle layers turn a meal into chyme.",
    bloodSupply: "Branches of the celiac trunk",
    funFact: "Its lining replaces surface cells rapidly to withstand an environment acidic enough to unfold many proteins.",
    tissue: "Gastric mucosa and glands",
    comparison: "Stomach vs. intestine",
    conditions: ["Gastritis", "Peptic ulcer disease", "Gastroesophageal reflux", "Gastroparesis", "Gastric polyps", "Hiatal hernia", "Gastric cancer", "Pyloric stenosis"],
    illustrated: false,
    hotspots: [
      { id: "cardia", label: "Cardia", detail: "Receives food from the esophagus", position: [-0.65, 1.2, 0.55], color: "#6393d8" },
      { id: "fundus", label: "Fundus", detail: "Rounded upper reservoir", position: [0.45, 1.2, 0.65], color: "#d89bc4" },
      { id: "body", label: "Body", detail: "Main mixing chamber", position: [0.35, 0.05, 0.85], color: "#ee7c6a" },
      { id: "pylorus", label: "Pylorus", detail: "Controls emptying into the duodenum", position: [-0.85, -1.05, 0.55], color: "#f2a33b" },
    ],
  },
  {
    id: "skeleton",
    name: "Skeleton",
    scientificName: "Systema skeletale",
    system: "Skeletal System",
    model: "procedural:skeleton",
    icon: "⌘",
    accent: "#c7ad86",
    description: "The body’s framework of bones, cartilage, and ligaments, built to support movement, protect organs, store minerals, and house blood-forming marrow.",
    poetic: "The living scaffold",
    size: "206 bones in the typical adult skeleton",
    weight: "Roughly 12–15% of body mass",
    location: "From the skull to the bones of the feet",
    function: "Supports, protects, stores minerals, and enables movement",
    dailyFact: "Constantly remodels old and new bone",
    medical: "Axial bones form the central support while appendicular bones create the levers of the limbs.",
    bloodSupply: "Nutrient, periosteal, metaphyseal, and epiphyseal vessels",
    funFact: "Bone is living tissue: cells continually remove tiny regions and rebuild them in response to load and mineral needs.",
    tissue: "Compact bone, spongy bone, and marrow",
    comparison: "Skeleton vs. muscles",
    conditions: ["Osteoporosis", "Fracture", "Osteoarthritis", "Scoliosis", "Osteomyelitis", "Rickets", "Paget disease of bone", "Osteosarcoma"],
    illustrated: false,
    hotspots: [
      { id: "skull", label: "Skull", detail: "Protects the brain and shapes the face", position: [0, 1.65, 0.55], color: "#c7ad86" },
      { id: "spine", label: "Vertebral Column", detail: "Supports the trunk and encloses the spinal cord", position: [0, 0.45, 0.55], color: "#6393d8" },
      { id: "ribcage", label: "Thoracic Cage", detail: "Guards the heart and lungs", position: [0.55, 0.75, 0.55], color: "#ee7c6a" },
      { id: "pelvis", label: "Pelvis", detail: "Transfers trunk weight to the legs", position: [0, -0.55, 0.6], color: "#d89bc4" },
      { id: "femur", label: "Femur", detail: "The body’s longest bone", position: [0.48, -1.35, 0.5], color: "#f2a33b" },
    ],
  },
  {
    id: "muscles",
    name: "Muscles",
    scientificName: "Musculi skeletales",
    system: "Muscular System",
    model: "procedural:muscles",
    icon: "∿",
    accent: "#b95f56",
    description: "Hundreds of skeletal muscles pull on tendons and bones to create movement, stabilize joints, maintain posture, and generate heat.",
    poetic: "The body in motion",
    size: "More than 600 named skeletal muscles",
    weight: "About 30–40% of body mass in many adults",
    location: "Layered throughout the face, trunk, and limbs",
    function: "Creates movement, posture, stability, and heat",
    dailyFact: "Makes countless coordinated contractions",
    medical: "Motor units let the nervous system grade force from delicate control to powerful whole-limb movement.",
    bloodSupply: "Regional muscular branches of nearby arteries",
    funFact: "Muscles can pull but cannot push, so many movements depend on opposing muscle groups taking turns.",
    tissue: "Skeletal muscle fibers and fascicles",
    comparison: "Muscles vs. skeleton",
    conditions: ["Muscle strain", "Tendinopathy", "Muscular dystrophy", "Myositis", "Rhabdomyolysis", "Myasthenia gravis", "Fibromyalgia", "Sarcopenia"],
    illustrated: false,
    hotspots: [
      { id: "deltoid", label: "Deltoid", detail: "Raises and stabilizes the arm", position: [0.85, 0.95, 0.65], color: "#ee7c6a" },
      { id: "pectoralis", label: "Pectoralis Major", detail: "Moves the arm across the chest", position: [0.4, 0.65, 0.8], color: "#f2a33b" },
      { id: "rectus", label: "Rectus Abdominis", detail: "Flexes and braces the trunk", position: [0, -0.05, 0.85], color: "#d89bc4" },
      { id: "quadriceps", label: "Quadriceps", detail: "Extends the knee", position: [0.45, -1.05, 0.75], color: "#6393d8" },
      { id: "gastrocnemius", label: "Gastrocnemius", detail: "Powers plantar flexion at the ankle", position: [-0.45, -1.6, 0.45], color: "#7fa88a" },
    ],
  },
  {
    id: "ear",
    name: "Ear",
    scientificName: "Auris",
    system: "Sensory System",
    model: "procedural:ear",
    icon: "◔",
    accent: "#c98673",
    description: "A layered sensory system that gathers sound, converts vibration into nerve signals, and measures head movement for balance.",
    poetic: "The keeper of sound",
    size: "Inner structures fit within the temporal bone",
    weight: "Only a few grams of sensory structures",
    location: "At each side of the head and within the temporal bone",
    function: "Supports hearing and equilibrium",
    dailyFact: "Tracks sound and head motion continuously",
    medical: "The cochlea handles hearing while the vestibular apparatus detects rotation and linear acceleration.",
    bloodSupply: "Posterior auricular, superficial temporal, and labyrinthine arteries",
    funFact: "The three semicircular canals sit in different planes, allowing the brain to detect rotation in three dimensions.",
    tissue: "Cochlear hair cells and vestibular epithelium",
    comparison: "Ear vs. eye",
    conditions: ["Otitis media", "Hearing loss", "Tinnitus", "Vertigo", "Ménière disease", "Otosclerosis", "Perforated eardrum", "Labyrinthitis"],
    illustrated: false,
    hotspots: [
      { id: "pinna", label: "Pinna", detail: "Funnels sound into the canal", position: [-1.15, 0.2, 0.65], color: "#ee7c6a" },
      { id: "eardrum", label: "Eardrum", detail: "Vibrates with incoming sound", position: [-0.25, 0.15, 0.75], color: "#f2a33b" },
      { id: "ossicles", label: "Ossicles", detail: "Three tiny bones amplify vibration", position: [0.25, 0.25, 0.7], color: "#c7ad86" },
      { id: "cochlea", label: "Cochlea", detail: "Converts vibration into neural signals", position: [0.9, -0.1, 0.8], color: "#6393d8" },
      { id: "canals", label: "Semicircular Canals", detail: "Sense rotational movement", position: [0.85, 0.75, 0.6], color: "#d89bc4" },
    ],
  },
  {
    id: "spinal-cord",
    name: "Spinal Cord",
    scientificName: "Medulla spinalis",
    system: "Nervous System",
    model: "procedural:spinal-cord",
    icon: "⋮",
    accent: "#d4a16f",
    description: "A long column of nervous tissue that relays information between brain and body and organizes rapid reflexes close to their source.",
    poetic: "The signal highway",
    size: "About 42–45 cm long in adults",
    weight: "Approximately 30–35 g",
    location: "Within the vertebral canal, ending near L1–L2",
    function: "Carries sensory, motor, and reflex signals",
    dailyFact: "Coordinates signals for every region below the head",
    medical: "Thirty-one pairs of spinal nerves connect cord segments with predictable regions of skin and muscle.",
    bloodSupply: "Anterior and paired posterior spinal arteries",
    funFact: "Some protective reflexes are organized in the spinal cord before the brain has consciously registered what happened.",
    tissue: "Central gray matter and surrounding white matter",
    comparison: "Spinal cord vs. brain",
    conditions: ["Spinal cord injury", "Transverse myelitis", "Spinal stenosis", "Syringomyelia", "Multiple sclerosis", "Spina bifida", "Cord compression", "Amyotrophic lateral sclerosis"],
    illustrated: false,
    hotspots: [
      { id: "cervical", label: "Cervical Enlargement", detail: "Supplies the upper limbs", position: [0, 1.15, 0.65], color: "#ee7c6a" },
      { id: "thoracic", label: "Thoracic Cord", detail: "Connects with the trunk", position: [0, 0.35, 0.65], color: "#f2a33b" },
      { id: "lumbar", label: "Lumbar Enlargement", detail: "Supplies the lower limbs", position: [0, -0.75, 0.65], color: "#6393d8" },
      { id: "roots", label: "Nerve Roots", detail: "Join to form spinal nerves", position: [0.75, -0.05, 0.55], color: "#d89bc4" },
      { id: "cauda", label: "Cauda Equina", detail: "Bundle of lower nerve roots", position: [0.2, -1.55, 0.5], color: "#7fa88a" },
    ],
  },
  {
    id: "bladder",
    name: "Bladder",
    scientificName: "Vesica urinaria",
    system: "Urinary System",
    model: "procedural:bladder",
    icon: "◡",
    accent: "#d49a68",
    description: "A stretchable muscular reservoir that receives urine from the ureters and stores it until coordinated emptying through the urethra.",
    poetic: "The quiet reservoir",
    size: "Comfortably holds about 400–600 mL in many adults",
    weight: "Varies with filling",
    location: "Behind the pubic bones in the pelvis",
    function: "Stores and releases urine",
    dailyFact: "Fills and empties several times each day",
    medical: "The detrusor muscle and urinary sphincters coordinate storage with voluntary and reflex control.",
    bloodSupply: "Superior and inferior vesical arteries",
    funFact: "As it fills, folds in the inner lining flatten so volume can rise without a matching jump in pressure.",
    tissue: "Transitional epithelium and detrusor muscle",
    comparison: "Bladder vs. kidneys",
    conditions: ["Urinary tract infection", "Overactive bladder", "Urinary retention", "Interstitial cystitis", "Bladder stones", "Urinary incontinence", "Neurogenic bladder", "Bladder cancer"],
    illustrated: false,
    hotspots: [
      { id: "ureters", label: "Ureters", detail: "Deliver urine from the kidneys", position: [0.7, 1.0, 0.55], color: "#6393d8" },
      { id: "detrusor", label: "Detrusor Muscle", detail: "Contracts to empty the bladder", position: [0.6, 0.05, 0.8], color: "#ee7c6a" },
      { id: "trigone", label: "Trigone", detail: "Smooth region between the openings", position: [0, -0.55, 0.85], color: "#f2a33b" },
      { id: "urethra", label: "Urethra", detail: "Carries urine out of the body", position: [0, -1.35, 0.55], color: "#d89bc4" },
    ],
  },
  {
    id: "thyroid",
    name: "Thyroid",
    scientificName: "Glandula thyroidea",
    system: "Endocrine System",
    model: "procedural:thyroid",
    icon: "⋈",
    accent: "#b96d63",
    description: "A butterfly-shaped endocrine gland whose hormones help set the pace of metabolism, growth, temperature regulation, and cardiovascular activity.",
    poetic: "The metabolic metronome",
    size: "About 4–6 cm across",
    weight: "Usually about 20–30 g",
    location: "Front of the neck, wrapped around the upper trachea",
    function: "Produces hormones that regulate metabolic activity",
    dailyFact: "Continuously adjusts hormone output through feedback",
    medical: "Follicles store thyroid hormone precursor outside their cells, an unusual arrangement among endocrine glands.",
    bloodSupply: "Superior and inferior thyroid arteries",
    funFact: "Despite its small size, it receives a rich blood supply so hormone output can respond efficiently to feedback signals.",
    tissue: "Thyroid follicles and parafollicular cells",
    comparison: "Thyroid vs. pancreas",
    conditions: ["Hypothyroidism", "Hyperthyroidism", "Hashimoto thyroiditis", "Graves disease", "Thyroid nodules", "Goiter", "Thyroiditis", "Thyroid cancer"],
    illustrated: false,
    hotspots: [
      { id: "right-lobe", label: "Right Lobe", detail: "One half of the gland", position: [-0.75, 0.15, 0.75], color: "#ee7c6a" },
      { id: "left-lobe", label: "Left Lobe", detail: "Mirrors the opposite lobe", position: [0.75, 0.15, 0.75], color: "#f2a33b" },
      { id: "isthmus", label: "Isthmus", detail: "Connects the two lobes", position: [0, -0.25, 0.95], color: "#d89bc4" },
      { id: "trachea", label: "Tracheal Relationship", detail: "The gland hugs the airway", position: [0, 0.65, 0.35], color: "#6393d8" },
    ],
  },
  {
    id: "lymphatic",
    name: "Spleen & Lymph Nodes",
    scientificName: "Systema lymphaticum",
    system: "Lymphatic & Immune System",
    model: "procedural:lymphatic",
    icon: "⁙",
    accent: "#a85e70",
    description: "A distributed defense and fluid-return network in which lymph vessels and nodes survey tissue fluid while the spleen filters blood.",
    poetic: "The watchful network",
    size: "The spleen is roughly 12 cm long; nodes are usually millimetres across",
    weight: "The spleen commonly weighs about 150 g",
    location: "Nodes follow vessels throughout the body; the spleen sits upper left abdomen",
    function: "Returns tissue fluid and supports immune surveillance",
    dailyFact: "Filters lymph and blood around the clock",
    medical: "Lymph nodes expose immune cells to material arriving from defined drainage regions, while the spleen monitors the bloodstream.",
    bloodSupply: "Splenic artery; nodal branches from regional vessels",
    funFact: "Unlike lymph nodes, which filter lymph, the spleen filters blood and can remove aging red blood cells from circulation.",
    tissue: "Lymphoid follicles, red pulp, and white pulp",
    comparison: "Lymphatic network vs. bloodstream",
    conditions: ["Lymphadenopathy", "Lymphedema", "Splenomegaly", "Lymphoma", "Splenic rupture", "Tonsillitis", "Lymphangitis", "Immune deficiency"],
    illustrated: false,
    hotspots: [
      { id: "spleen", label: "Spleen", detail: "Filters blood and supports immune responses", position: [1.05, 0.65, 0.65], color: "#a85e70" },
      { id: "cervical", label: "Cervical Nodes", detail: "Drain the head and neck", position: [0, 1.45, 0.55], color: "#6393d8" },
      { id: "axillary", label: "Axillary Nodes", detail: "Drain the upper limbs and chest", position: [-0.85, 0.75, 0.55], color: "#ee7c6a" },
      { id: "thoracic-duct", label: "Thoracic Duct", detail: "Returns much of the body’s lymph to blood", position: [0.1, 0.2, 0.65], color: "#f2a33b" },
      { id: "inguinal", label: "Inguinal Nodes", detail: "Drain the lower limb and lower trunk", position: [-0.55, -1.15, 0.55], color: "#d89bc4" },
    ],
  },
  {
    id: "female-reproductive",
    name: "Uterus & Ovaries",
    scientificName: "Organa genitalia feminina",
    system: "Reproductive System",
    model: "procedural:female-reproductive",
    icon: "⌇",
    accent: "#bf718b",
    description: "A coordinated reproductive system in which ovaries release oocytes and hormones while the uterine tube and uterus support transport, implantation, and pregnancy.",
    poetic: "The cycle of possibility",
    size: "A nonpregnant uterus is roughly 7–8 cm long",
    weight: "Often about 50–80 g before pregnancy",
    location: "Within the pelvis between the bladder and rectum",
    function: "Produces oocytes and supports fertilization, implantation, and pregnancy",
    dailyFact: "Changes continuously across the reproductive cycle",
    medical: "The endometrium responds to ovarian hormones while the muscular myometrium provides the force of labor.",
    bloodSupply: "Uterine and ovarian arteries",
    funFact: "During pregnancy the uterus expands dramatically, then gradually returns toward its earlier size after birth.",
    tissue: "Endometrium, myometrium, and ovarian follicles",
    comparison: "Uterus and ovaries vs. testes and prostate",
    conditions: ["Endometriosis", "Uterine fibroids", "Ovarian cysts", "Polycystic ovary syndrome", "Pelvic inflammatory disease", "Endometrial cancer", "Ovarian cancer", "Uterine prolapse"],
    illustrated: false,
    hotspots: [
      { id: "uterus", label: "Uterus", detail: "Supports implantation and pregnancy", position: [0, 0.1, 0.9], color: "#bf718b" },
      { id: "endometrium", label: "Endometrium", detail: "Inner lining that changes across the cycle", position: [0, 0.4, 1.0], color: "#ee7c6a" },
      { id: "tubes", label: "Uterine Tubes", detail: "Carry the oocyte toward the uterus", position: [0.75, 0.7, 0.65], color: "#f2a33b" },
      { id: "ovaries", label: "Ovaries", detail: "Release oocytes and hormones", position: [-1.2, 0.55, 0.75], color: "#d89bc4" },
      { id: "cervix", label: "Cervix", detail: "Lower uterine passage", position: [0, -0.85, 0.75], color: "#6393d8" },
    ],
  },
  {
    id: "male-reproductive",
    name: "Testes & Prostate",
    scientificName: "Organa genitalia masculina",
    system: "Reproductive System",
    model: "procedural:male-reproductive",
    icon: "⌁",
    accent: "#a97565",
    description: "A reproductive network in which the testes produce sperm and testosterone while ducts and glands prepare and transport seminal fluid.",
    poetic: "The generative pathway",
    size: "Each testis is about 4–5 cm long; the prostate is walnut-sized",
    weight: "Each testis about 15–25 g; prostate about 20–30 g",
    location: "Testes within the scrotum; prostate below the bladder",
    function: "Produces sperm and reproductive hormones, then supports transport",
    dailyFact: "Maintains sperm production after puberty",
    medical: "Sperm mature in the epididymis before traveling through the ductus deferens and joining glandular secretions.",
    bloodSupply: "Testicular, deferential, and prostatic arterial branches",
    funFact: "The pampiniform venous plexus exchanges heat with incoming arterial blood to help keep the testes cooler than core temperature.",
    tissue: "Seminiferous tubules and prostatic glands",
    comparison: "Testes and prostate vs. uterus and ovaries",
    conditions: ["Benign prostatic hyperplasia", "Prostatitis", "Prostate cancer", "Testicular torsion", "Testicular cancer", "Epididymitis", "Varicocele", "Male factor infertility"],
    illustrated: false,
    hotspots: [
      { id: "testes", label: "Testes", detail: "Produce sperm and testosterone", position: [-0.55, -1.05, 0.75], color: "#a97565" },
      { id: "epididymis", label: "Epididymis", detail: "Supports sperm maturation", position: [0.55, -0.85, 0.85], color: "#f2a33b" },
      { id: "ductus", label: "Ductus Deferens", detail: "Transports sperm toward the pelvis", position: [0.65, 0.25, 0.65], color: "#6393d8" },
      { id: "vesicles", label: "Seminal Vesicles", detail: "Add nutrient-rich glandular fluid", position: [0.55, 0.85, 0.75], color: "#d89bc4" },
      { id: "prostate", label: "Prostate", detail: "Surrounds the upper urethra", position: [0, 0.2, 0.9], color: "#ee7c6a" },
    ],
  },
  {
    id: "gallbladder",
    name: "Gallbladder",
    scientificName: "Vesica biliaris",
    system: "Digestive System",
    model: "procedural:gallbladder",
    icon: "◜",
    accent: "#8d9e5d",
    description: "A small pear-shaped sac that stores and concentrates bile, then releases it into the small intestine when dietary fat arrives.",
    poetic: "The keeper of bile",
    size: "Usually about 7–10 cm long",
    weight: "Varies with its bile volume",
    location: "Tucked beneath the right lobe of the liver",
    function: "Stores, concentrates, and releases bile",
    dailyFact: "Concentrates bile between meals",
    medical: "Contraction of the gallbladder and relaxation of the biliary outlet help deliver bile into the duodenum.",
    bloodSupply: "Cystic artery, usually from the right hepatic artery",
    funFact: "People can live without a gallbladder because the liver still makes bile; storage and timing simply change.",
    tissue: "Folded columnar mucosa and smooth muscle",
    comparison: "Gallbladder vs. liver",
    conditions: ["Gallstones", "Cholecystitis", "Biliary colic", "Choledocholithiasis", "Cholangitis", "Gallbladder polyps", "Biliary dyskinesia", "Gallbladder cancer"],
    illustrated: false,
    hotspots: [
      { id: "fundus", label: "Fundus", detail: "Rounded distal end", position: [0, -0.85, 0.85], color: "#8d9e5d" },
      { id: "body", label: "Body", detail: "Main storage chamber", position: [0, 0.05, 0.9], color: "#ee7c6a" },
      { id: "neck", label: "Neck", detail: "Narrows toward the cystic duct", position: [0.25, 0.85, 0.75], color: "#f2a33b" },
      { id: "cystic-duct", label: "Cystic Duct", detail: "Joins the biliary tree", position: [0.8, 1.15, 0.55], color: "#6393d8" },
    ],
  },
  {
    id: "airway-diaphragm",
    name: "Airway & Diaphragm",
    scientificName: "Viae respiratoriae",
    system: "Respiratory System",
    model: "procedural:airway-diaphragm",
    icon: "ϟ",
    accent: "#7794ad",
    description: "A coordinated passage and pump in which the trachea conducts air, the esophagus carries food behind it, and the diaphragm changes chest volume for breathing.",
    poetic: "The crossing of breath",
    size: "Trachea about 10–12 cm; diaphragm spans the lower ribcage",
    weight: "A composite of airway and skeletal muscle structures",
    location: "From the lower neck through the chest to its muscular floor",
    function: "Conducts air, protects swallowing, and powers ventilation",
    dailyFact: "The diaphragm drives most quiet breaths",
    medical: "Cartilage keeps the trachea open, peristalsis moves food through the esophagus, and diaphragm contraction enlarges the thorax.",
    bloodSupply: "Inferior thyroid, bronchial, esophageal, and phrenic arteries",
    funFact: "The esophagus passes through its own opening in the diaphragm before joining the stomach below the chest.",
    tissue: "Ciliated airway epithelium, smooth muscle, and skeletal muscle",
    comparison: "Airway and diaphragm vs. lungs",
    conditions: ["Asthma", "Tracheal stenosis", "Gastroesophageal reflux", "Hiatal hernia", "Diaphragmatic paralysis", "Tracheitis", "Esophagitis", "Aspiration"],
    illustrated: false,
    hotspots: [
      { id: "trachea", label: "Trachea", detail: "Cartilage-supported airway", position: [-0.35, 1.15, 0.75], color: "#6393d8" },
      { id: "esophagus", label: "Esophagus", detail: "Muscular food passage behind the airway", position: [0.4, 0.75, 0.55], color: "#d89bc4" },
      { id: "carina", label: "Carina", detail: "Point where the trachea divides", position: [-0.25, 0.05, 0.8], color: "#f2a33b" },
      { id: "diaphragm", label: "Diaphragm", detail: "Primary muscle of quiet breathing", position: [0, -1.05, 0.75], color: "#ee7c6a" },
      { id: "hiatus", label: "Esophageal Hiatus", detail: "Opening for the esophagus", position: [0.45, -0.85, 0.85], color: "#7fa88a" },
    ],
  },
];

